# Generated by Django 5.0.1 on 2025-04-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem', models.TextField()),
                ('heart_rate', models.FloatField()),
                ('bp_sys', models.FloatField()),
                ('bp_dia', models.FloatField()),
                ('temp', models.FloatField()),
                ('spo2', models.FloatField()),
                ('opd', models.CharField(max_length=100)),
                ('urgency', models.IntegerField()),
            ],
        ),
    ]
