# Generated by Django 5.0.1 on 2025-04-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=200)),
                ('heart_rate', models.FloatField()),
                ('bp_sys', models.FloatField()),
                ('bp_dia', models.FloatField()),
                ('temp', models.FloatField()),
                ('spo2', models.FloatField()),
                ('urgency', models.IntegerField()),
                ('opd', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
