# Generated by Django 5.0.1 on 2025-04-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_deletedpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
            ],
        ),
    ]
